FROM python:3.12-slim AS builder

WORKDIR /app
ENV POETRY_VIRTUALENVS_CREATE=false

RUN apt-get update && apt-get install -y build-essential cmake meson ninja-build git patchelf && rm -rf /var/lib/apt/lists/* && pip install poetry nuitka

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --without dev

COPY . .
RUN nuitka --standalone --jobs=4 --lto=yes capitals4py/main.py -o capitals4py.bin


FROM debian:12-slim

WORKDIR /app
COPY --from=builder /app/main.dist /app

EXPOSE 8080

ENV DIR_PROJECT=/app
ENV ENV=prod

ENTRYPOINT ["./capitals4py.bin"]
